CREATE TABLE IF NOT EXISTS ledger_rules (
    rule_id TEXT PRIMARY KEY,
    field TEXT NOT NULL,
    left_pattern TEXT NOT NULL,
    right_pattern TEXT NOT NULL,
    normalized_key TEXT NOT NULL,
    decision TEXT NOT NULL,
    source_case_id TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    created_by TEXT NOT NULL DEFAULT 'pilot',
    revoked_at TEXT,
    note TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS pilot_reviews (
    review_id TEXT PRIMARY KEY,
    case_id TEXT NOT NULL,
    field TEXT NOT NULL,
    decision TEXT NOT NULL,
    promote_to_ledger INTEGER NOT NULL DEFAULT 1,
    reviewer TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS case_runs (
    run_id TEXT PRIMARY KEY,
    case_id TEXT NOT NULL,
    email_id TEXT NOT NULL,
    verdict TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ledger_active ON ledger_rules(active, field);
CREATE INDEX IF NOT EXISTS idx_runs_email ON case_runs(email_id);

CREATE TABLE IF NOT EXISTS llm_cache (
    cache_key TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS email_verdicts (
    email_id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    status TEXT,
    review_reason TEXT,
    has_defect INTEGER NOT NULL DEFAULT 0,
    defect_fields_json TEXT NOT NULL DEFAULT '[]',
    payload_json TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pipeline_jobs (
    job_id TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    total INTEGER NOT NULL DEFAULT 0,
    processed INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    payload_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    status INTEGER NOT NULL,
    ip TEXT NOT NULL DEFAULT '',
    request_id TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_verdicts_category ON email_verdicts(category);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON pipeline_jobs(status, updated_at);

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
    key_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    last_used_at TEXT,
    revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS stored_objects (
    object_key TEXT PRIMARY KEY,
    backend TEXT NOT NULL,
    bytes INTEGER NOT NULL DEFAULT 0,
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    uri TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_objects_created ON stored_objects(created_at);

CREATE TABLE IF NOT EXISTS inbox_emails (
    email_id TEXT PRIMARY KEY,
    subject TEXT NOT NULL DEFAULT '',
    from_addr TEXT NOT NULL DEFAULT '',
    body_text TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL DEFAULT '{}',
    attachments_json TEXT NOT NULL DEFAULT '[]',
    attachment_count INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'official',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_inbox_source ON inbox_emails(source, email_id);
