"""Snapshot a live backend into web/lib/demo-data.js for offline (static HTTPS) demos.

Usage:
    py -3 scripts/capture_demo_data.py [--api http://127.0.0.1:8000]

The Bridge falls back to this file whenever /api/runs is unreachable, and
simulates the ledger / replay / chaos / autonomy loop client-side.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "web" / "lib" / "demo-data.js"
CHAOS_TYPES = ["attachment_corrupt", "ocr_garble", "llm_timeout", "empty_email"]
CHAOS_TARGET = "demo_si_vs_bl"


def call(base: str, path: str, method: str = "GET", body: dict | None = None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        base + path,
        data=data,
        method=method,
        headers={"Content-Type": "application/json"} if data is not None else {},
    )
    with urllib.request.urlopen(req, timeout=300) as resp:
        return json.loads(resp.read())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--api", default="http://127.0.0.1:8000")
    args = ap.parse_args()
    base = args.api.rstrip("/")

    print(f"[capture] seeding via {base} ...")
    call(base, "/api/demo/seed", "POST", {})
    runs = call(base, "/api/runs")
    print(f"[capture] {len(runs)} runs")

    emails = {}
    for run in runs:
        eid = run["email_id"]
        if eid in emails:
            continue
        try:
            emails[eid] = call(base, f"/api/emails/{eid}")
        except Exception as exc:  # noqa: BLE001
            print(f"[capture] email {eid} skipped: {exc}")

    chaos = {}
    for kind in CHAOS_TYPES:
        try:
            chaos[kind] = call(base, f"/api/chaos/{kind}", "POST", {"email_id": CHAOS_TARGET})
            print(f"[capture] chaos {kind} -> {chaos[kind]['card']['verdict']}")
        except Exception as exc:  # noqa: BLE001
            print(f"[capture] chaos {kind} failed: {exc}")

    autonomy = call(base, "/api/autonomy")

    # Chaos runs were written to the ledger; reseed so the live board is clean again.
    call(base, "/api/demo/seed", "POST", {})

    dump = lambda obj: json.dumps(obj, ensure_ascii=False, separators=(",", ":"))  # noqa: E731
    OUT.write_text(
        "// Generated by scripts/capture_demo_data.py from a live Harbormaster backend.\n"
        "// Used only when the API is unreachable (static HTTPS hosting without FastAPI).\n"
        f"export const DEMO_RUNS = {dump(runs)};\n"
        f"export const DEMO_EMAILS = {dump(emails)};\n"
        f"export const DEMO_CHAOS = {dump(chaos)};\n"
        f"export const DEMO_AUTONOMY = {dump(autonomy)};\n",
        encoding="utf-8",
    )
    print(f"[capture] wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
